### PR TITLE
[DNM] don't rename fields on join

### PR DESCRIPTION
**Pull request by tomwayson**
@benstoltz 

Tests are passing locally for me, and all cedar dummy pages work.

This now has the changes needed to demonstrate my idea for how we could remove the need for `datasets[i].id` and `series[j].datasteId`.

What I did was:

 - don't append dataset index to field name when joining datasets
 - render just iterates through series when making graphs, not datasets and series

lmk what you think and I will do the following

TODO:
- [x] actually remove `datasets[i].id` and `series[j].datasteId` from dummy specs
- [x] test a chart that "merges" (i.e. `merge: true`) datasets
- [x] add'l charts (multiple scatter, stacked bar)?

### CODE REVIEW

**Comment by tomwayson** [comment]
Looks like the changes I've made have broken radar charts - only showing the first series right now:

image

Should look like: 

image

**Comment by tomwayson** [comment]
As of 94f871c all dummy pages except the scatter plot page are working.

However, there are a lot of problems w/ the scatter page - both in the example itself and how the library is handling scatter plots. It's not even clear what that page is trying to demonstrate at this point - it's been reworked so many times.  It says that it should "illustrate a method for the graphing of multiple scatterplots of data utilizing two queries of a Geoservice and two series of a query." I seem to recall somewhere along the line an earlier version of that example had multiple colors (each it's own series?), but I can't find that. [This version](https://esridc.github.io/cedar-amcharts/scatter.html) does not.

What I'm concerned about w/in the context of this PR is that on this branch, it looks like this:

image

But in the base branch, it looks like:

image

And I'm not sure what changes in this PR have caused the difference.

I'm currently trying to rework that example so that it's more of a basic scatterplot (1 dataset, 1 series) and getting working the way that we think it should, and then I think we can think through a new multi-series scatterplot example either in this PR or later.

**Comment by tomwayson** [comment]
@ajturner 

FYI - the dummy pages from this branch are up at http://cedar-v1.surge.sh/

and the crux of this PR is this line: 

https://github.com/Esri/cedar/pull/277/files#diff-ca41177b1dcd9a1586921bd17ff13adaR49

Just about all the other changes in here are to support ^^^ by either making the tests pass,  dummy pages work, updating datasets or renaming variables for clarity, or adding comments.

**Comment by ajturner** [comment]
@tomwayson if you don't append `_{datasetIndex}`, then how do you merge multiple datasets together that may have the same attribute names?

For example, the [multiple bars from different queries](https://esridc.github.io/cedar-amcharts/bar-multiple.html) example

**Comment by tomwayson** [comment]
@ajturner you just don't use the same attribute name. See [my rework of that example](http://cedar-v1.surge.sh/bar-multiple.html) that is [included in this PR](https://github.com/Esri/cedar/pull/277/files#diff-96ea50990dfa41af719619cda6d420a8).

Whenever anyone is doing summary queries, they can name the `outStatisticFieldName` whatever they want, so we'll just require them to choose unique names. 

The only problem is when they are joining non-summary queries, b/c I'm not aware of any params you can send to a non-summary query to have it return different names. I had an idea for how to handle that though. Each `dataset` could include an optional `reanameFields: { SOME_FIELD: 'SOME_FIELD_1', AnotherField: 'whateves' }` property. That is not included in this PR, but it can be if you think that makes sense.

Nor does this PR include any code to ensure that users choose unique names. We might be able to add that, but we can only check once we have all the records back. I think we're also going to have to rely on docs to educate users that that all datasets are going to be merged or joined into a single virtual table, and that is what the `series` are going to operate on.

**Comment by ajturner** [comment]
We should not require users to have to rename any fields. The goal is to remove any idiosyncrasies of Geoservices API or Chart API.

It's not clear to me why we can't use the pattern originally proposed to append the dataset index?

**Comment by benstoltz** [comment]
@ajturner The original pattern seems (to me) to need a relationship between the dataset and the corresponding series. Previously in cedar-amcharts with the old spec we had that relation, which we no longer do (as they are both arrays). I originally handled that by putting an `id` prop on each dataset with a corresponding `datasetId` on respective series. This might not have been the proper or best way to handle it but it's what I could figure out. (To explain why Tom was trying a different method)

**Comment by tomwayson** [comment]
because that pattern requires for any join to either:
- add an `id` to each dataset and `datasetId` to each series, or
- have a 1:1 relationship between datasets and series and keep them in the same order

We should not limit joins to a 1:1, that's why @benstoltz added `id` and `datasetId`. While that worked, I think that is exposing the idiosyncrasies of our own API, and more verbose than what I've proposed.

I don't think this is really an "idiosyncrasies of Geoservices API or Chart API" leaking through. If the users is trying to merge two datasets w/ the same field name, I don't think it's unreasonable to ask them how they want to handle the collision since the only way (that I can think of) for us to be smart about it would be to limit them to 1:1 datasets:series.

**Comment by ajturner** [comment]
Ok - I actually don't yet understand the issues or changes, but I think that's ok. We are essentially limiting to say that columns must be unique. We can later come back to this design if it's an issue and should be an API transparent change.

**Comment by tomwayson** [comment]
Leaving this open for discussion based on @ajturner's comments in slack:

> I think we can expand the JSON to have 'named merges', much like Vega `source`

```{ 
'datasets': [ 
  { 'name': 'schools', ...},
  { 'name': 'schools', ...},
  { 'name': 'demographics', ...}],
'series' [
  { 'source': 'demographics', ...},
  { 'source': 'schools', ...}
]}```

That is essentially what this PR removes. In the base branch @benstoltz  used `id` instead of `name` and `datasetId` instead of `source` but it's exactly the same idea.

I prefer the solution proposed in this PR, but if the consensus is in favor of either `dataset[i].id` w/ `series.datasetId` (or `dataset[i].name` w/ `series.source`) then I will close this.

**Comment by ajturner** [comment]
We need to support Rename b/c ArcGIS Service aggregations always return `Expr_1` and this isn't changeable.

See https://github.com/Esri/cedar/blob/v1-beta/packages/cedar/test/dummy/radar.html#L65

**Comment by tomwayson** [comment]
True, but FWIW I did propose a solution for that above:
> Each `dataset` could include an optional `renameFields: { SOME_FIELD: 'SOME_FIELD_1', AnotherField: 'whateves' }` property.

So `renameFields: { EXPR_1: 'HOURLY_SUM_THEFT', ... }`

**Comment by tomwayson** [comment]
I'm conceding to @ajturner and @benstoltz b/c it's 2 to 1, even though I'm right 😜. If nothing else I think it's telling that I've had to lobby pretty hard for my way and do a lot of 'splainin' in this PR and neither of you seems to see the light.

I will close this PR once @benstoltz opens a new one to change the names of `datasets[i].id` and `series[j].datasteId` to `datasets[i].name` and `series[j].source`. That PR should may want to consider making a few of the minor changes addressed in this PR:

- [change the cedar package name to `arcgis-cedar`](https://github.com/Esri/cedar/pull/277/files?w=1#diff-cfc903b588be63cd9a780a17086574b8L2)
- [update the bar-multiple example to get rid of `mappings` and use series](https://github.com/Esri/cedar/pull/277/files?w=1#diff-96ea50990dfa41af719619cda6d420a8L127)
- [consider using the tornado dataset for the bubble example b/c I think it works better](https://github.com/Esri/cedar/blob/bfa7e0ec9c9d6457e637bdea5f3535614a8a9fef/packages/cedar/test/dummy/bubble.html) - ditto for [scatter](https://github.com/Esri/cedar/blob/bfa7e0ec9c9d6457e637bdea5f3535614a8a9fef/packages/cedar/test/dummy/scatter.html)
- [include the multiple scatter example](https://github.com/Esri/cedar/blob/bfa7e0ec9c9d6457e637bdea5f3535614a8a9fef/packages/cedar/test/dummy/scatter-multiple.html)
- [comment out missing links to missing test files](https://github.com/Esri/cedar/pull/277/files?w=1#diff-0f07ff267be31a562dd9d076cd1c7753R20)

The rest of the changes were either specific to the logic of this PR or renaming/comments of the current code to help me understand it. All of which can be tossed when we close this PR.

**Comment by tomwayson** [comment]
closing in favor of #312

**Pull request closed without merging**
