### PR TITLE
Upgraded to Vega2

### LINKED ISSUE #104: Ordinal bar charts need half-width space between bars
I didn't know about the `xc` property. This works:

vega_live_editor

```javascript
marks.x.properties.enter.xc = {"scale": "x", "field": "x", "offset": chart.width / data.length / 2}
marks.x.properties.enter.width = {"value": chart.width / data.length * 0.66 }
```

### PR DESCRIPTION
**Pull request by ajturner**
Vega2 was released and it's time to upgrade!

This fixes a number of bugs, and also will bring us ability to do signal interactions, zoom, cross-filtering, etc. 

- Ordinal Bars have half-width space - Resolves #104 
- local copies of D3 and Vega installed via NPM and grunt
- improved tooltip and other examples

banners_and_alerts_and_bar_chart___esri_cedar

I'm not sure the implications this has to the AMD work that @tomwayson  - but since we're note in JS API 3.14 - it seems ok to charge ahead with this and come back to AMD testing.

@dbouwman

### CODE REVIEW

**Comment by HeikoH** [comment]
nice!

**Comment by ajturner** [comment]
hrm - Travis is failing b/c it can't `npm install vega ~2.0.0`. but I installed it locally. wonder if it's a Travis npm cache issue or something else.

**Comment by HeikoH** [comment]
there is no 2.0.0 package yet, right? so how did you manage to install it locally? :confused:

**Comment by HeikoH** [comment]
locally:
```
npm install vega@~2.0.0
....
npm ERR! notarget No compatible version found: vega@'>=2.0.0 <2.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.1.0","1.2.0","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.4.0","1.4.1","1.4.2","1.4.3","1.5.0","1.5.3","1.5.4"]
...
```

**Comment by ajturner** [comment]
@HeikoH I'm not sure how it worked locally (but it did once). 

Seems like [Vega team is waiting for Monday](https://github.com/vega/vega/issues/293)

**Comment by ajturner** [comment]
@HeikoH do you want to merge this?

**Comment by ajturner** [comment]
@HeikoH [Vega2 has a release 2.0.1](https://github.com/vega/vega/releases) so updated to load the NPM module.

**Comment by HeikoH** [comment]
@ajturner code looks fine to me... A lot of examples are broken though (but that's not specific to this PR).
Would also be nice to list breaking changes.

**Comment by ajturner** [comment]
Thanks @HeikoH I believe that I fixed the demos. This was a mix of updated the AMD loaded JS files, a bad Pie specification and some other small checks.

**Comment by HeikoH** [comment]
@ajturner also update README.md, as it won't be valid anymore when this PR gets merged

**Comment by ajturner** [comment]
Yer good @HeikoH ! updated the README

**Pull request merged**
