### PR TITLE
adding at least some highlighting to the example JS code

### PR DESCRIPTION
**Pull request by chelm**
Its not perfect but it makes the sample easier to read...

### CODE REVIEW

**Comment by ajturner** [comment]
Thanks - I've been meaning to fix this.

Just need to see why Travis is failing though.

**Comment by chelm** [comment]
Yeah im not sure what's up with that failing test. This adds nothing that would impact the tests

**Comment by ajturner** [comment]
So this actually breaks Vega in a deep way

```javascript
prototype.insert = function(tuples) {
  var prev = this._revises ? null : undefined;
  var insert = tuples.map(function(d) {
    return Tuple.ingest(d, prev);
  });

  this._input.add = this._input.add.concat(insert);
  return this;
};

```

throws this error: 

```
Uncaught TypeError: tuples.map is not a function
28.prototype.insert @ DataSource.js:36
28.prototype.values @ DataSource.js:78
86.parseData.datasource @ data.js:46
(anonymous function) @ data.js:29
parseData @ data.js:24
parse @ spec.js:36
parseSpec @ spec.js:41
Cedar._renderSpec @ cedar.js:364
Cedar.update @ cedar.js:325
Cedar.show @ cedar.js:265
Cedar._purgeMethodQueue @ cedar.js:654
(anonymous function) @ cedar.js:139
(anonymous function) @ cedar.js:669
(anonymous function) @ d3.min.js:1
t @ d3.min.js:1
u @ d3.min.js:1
```

**Comment by chelm** [comment]
@ajturner interesting, so highlight over rides the prototype? Why dis the PR test pass but not the push.

**Comment by chelm** [comment]
s/highlight.js/prism.js - much better looking syntax highlighting too

**Comment by chelm** [comment]
ok wtf

**Comment by chelm** [comment]
I guess I could try to get the tests to pass locally :) They are failing for me on this one still...

**Comment by chelm** [comment]
I've removed the 3 lines added here and the tests still fail... /cc @ajturner

**Comment by chelm** [comment]
@ajturner are you sure travis is running the Cedar tests? The other PRs that "pass" don't seem to actually run tests, or Im failing to see assertions here: https://travis-ci.org/Esri/cedar/builds/71304413

**Comment by ajturner** [comment]
I pulled and ran locally and examples failed for me. Is there some other non checked in file?

**Comment by chelm** [comment]
Everything is checked in.

**Comment by chelm** [comment]
npm install fails on a couple deps and master tests fail w/no code changes.

**Comment by ajturner** [comment]
Can you copy and paste the errors?

**Comment by chelm** [comment]
Something is off in a few places. `site/build/js/vega.min.js` never gets copied as it seems to be missing from package.json but that package is relied on by the grunt "assemble" task.

**Comment by chelm** [comment]
screenshot 7 19 15 10 26 am-2

**Comment by chelm** [comment]
Having trouble installing vega locally via `npm install vega`

**Comment by chelm** [comment]
Ahh cairo wont install... this needs to be added to the README (we took this out of koop since it was such an annoying dep). I can add it later today. 

```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

**Comment by benstoltz** [comment]
Closing due to mucking a rebase up and minimal changes needed to enable Prism. Will PR those changes in a new branch.

**Pull request closed without merging**
