### PR TITLE
cedar.transform added in to allow user to mutate data from FR response

### PR DESCRIPTION
**Pull request by benstoltz**

### CODE REVIEW

**Comment by tomwayson** [comment]
Added an example that uses `.transform` to limit pie chart to 6 slices: top 5 + other:

image

**Comment by tomwayson** [comment]
When creating that example, I was happy w/ the API.

Still not sure about the name, maybe `.transformQueryResults` or `.transformResults`? I suggested `transform` to be consistent w/ other property/method names which are all terse. However, this property is a bit different, it's more akin to a lifecycle method - maybe `processQueryResults`?

thoughts @benstoltz, @ajturner, @dbouwman?

**Comment by dbouwman** [comment]
I think having `transform` in the name makes sense because that's what the fn() does.

How about `dataTransform(queryResult, dataset)`? I think you should also consider some soft of "format verification" on the result, so you can direct a dev to the likely location of the :boom:

I've not looked at Arcade, but it seems that it would drop into this function

**Comment by ajturner** [comment]
I'm almost always a fan of consistent, single word, terse but legible names. 

What other 'transform' methods will we have? Is there `transformData` and `transformGraphics`?

**Comment by tomwayson** [comment]
I don't think we'll have other `transformSomething` functions.

To me `.dataTransform` _feels_ like the best description of what this is - a _property_ that when set to a function, that function will be applied to the query results before assigning them to the specification's data.

```js
var chart = new Cedar({ type: "bar", dataset: {...}, dataTransform: function(featureSet, dataset) {...} }
``` 

vs.

```js
var chart = new Cedar({ type: "bar", dataset: {...}, transform: function(featureSet, dataset) {...} }`
```

That said, it only feels marginally better than `.transform`, and I think we've entered the realm of the subjective. So unless there is vocal opposition, we'll leave as is to be consistent w/ the other terse functions/props.

**Comment by tomwayson** [comment]
Also, I think that helps settle the "what should we name the public version of `_renderSpec()`" question that we'll face for #213 - it just becomes `render()`.

**Comment by ajturner** [comment]
You mention that when property transform is a function... what other types can it be? Does it actually make sense to be just `.data` that can be an object, array or function?

**Comment by tomwayson** [comment]
It can't (currently) be any other types, what I meant to say there is that if it's a function, it get's applied, if not, nothing happens.

So, the proposed `.data` property would work like:
 - If function: apply to query results.
 - If object: assume is a feature set, use `data.features` array.
 - If array: assume is an array of features.

Right?

If either of the latter two, what should cedar do if the definition also includes a `dataset` w/ a `url`/`query` or `data`? Should it give preference to `.data` or `._definition.dataset`?

Also, I want to keep in mind our upcoming need for multi-dataset charts. I've been assuming that would essentially involve deprecating `dataset` in favor of  `datasets` which would be either an array or hash of the current `dataset` JSON object. This is why I suggested that the transform function should receive the dataset as the second argument so that it could be conditionally applied only to specific datasets. That could still work in the case where `.data` is a function, but what about if it's an array or object?

To me `.transform` fills our immediate functional gap. `.data` also fills that gap, but is overloaded with functionality that already exists in one form or another and is going to change in the future, and therefore requires more thought.

I say we stick w/ `.transform` for now, and if we ever implement `.data` we can deprecate `.transform`.

**Pull request merged**
