### PR TITLE
Initial support for Histogram

### LINKED ISSUE #74: Support Histograms
Histograms are almost like bar charts except X-axis will show numeric intervals with some predefined breaks (equal intervals, natural breaks, etc.).

The implementation could probably use [getHistogram](https://devtopia.esri.com/WebGIS/arcgis-js-api/wiki/JSAPI-3.13-API-Reference#getHistogram) method from new JS API.

### PR DESCRIPTION
**Pull request by ajturner**
Making Progress...
- [ ] Missing maximum value (right-most x) 
- [ ] X-Labels need to be auto-placement
- [ ] Move or remove the x-ticks (unsuccessful in offset so far)
- [ ] Y-axis auto-placement needs to be adjusted 

esri_cedar

Resolves #74

/cc @abakirov @phlorah

### CODE REVIEW

**Comment by abakirov** [comment]
@ajturner 
Quick question: where is frequency calculation happening? It looks like all data is downloaded to the client as individual records and then binned on the client. If this is the case, will there be a way to provide pre-binned data?

**Comment by abakirov** [comment]
I'm thinking of having some hybrid algorithm in the client app that would do calculation on the client only up to certain threshold, say, 1000 records. Above that threshold we will have to do binning server-side.

**Comment by ajturner** [comment]
> Quick question: where is frequency calculation happening? It looks like all data is downloaded to the client as individual records and then binned on the client. If this is the case, will there be a way to provide pre-binned data?

is this example it is happening in the client. This is an important point that must be handled cleanly across the different clients of Cedar.

- Desktop/Pro will have in-memory arrays of data
- Web applications may have in-memory arrays
- if data backed by a service - use that service to generate statistics per JS API.

While Vega can load data from URL, for these reasons Cedar always sends an array of data to Vega. 

so @abakirov what should the API look like where the developer specifies "Here are data, you calculate the bins for me" vs. "Here are my bins, just give me a histogram"

**Comment by abakirov** [comment]
So there are two use cases:
1. Here are my bins, just give me a histogram
2. Here are data, you calculate the bins for me

API for use case 2 can be fully implemented on top of API for use case 1. I'd say we only implement use case 1 (for now?). To cover the second scenario we can create a sample in the docs showing how to use [getHistogram](https://developers.arcgis.com/javascript/jsapi/featurelayerstatistics-amd.html#gethistogram) method with Cedar. And Cedar already has [API for sending pre-calculated data](http://esri.github.io/cedar/examples/inlined-data.html), so we shouldn't need new API here, right? The bins can be sent in as feature set:
```
{
  features:[
    {
      attributes: {
        "TOTAL_STUD": 100,
        "COUNT": 9
      }
    },
    {
      attributes: {
        "TOTAL_STUD": 200,
        "COUNT": 4
      }
    },
... etc, other bins
  ]
}
```

Thoughts?

**Comment by ajturner** [comment]
The FeatureCollection example you have implies 100-200
And then 200-300 because of previous diff? What if the bins are quantile or max breaks and not equal interval?

I'd Iike to see what the JSAPI or Pro data structures are for bins.

**Comment by azhigimont** [comment]
I think desktop needs API to allow pre-calculated bins. Scientific data can be millions of points. I'm not sure JS will handle this case efficiently.

**Comment by ajturner** [comment]
@azhigimont definitely, that was always understood. One question is how will you send the data to the API?

[JS API getHistogram](https://developers.arcgis.com/javascript/jsapi/featurelayerstatistics-amd.html#gethistogram) returns:

```json
{ "bins": [ 
   { "minValue": 0, "maxValue": 56, "count": 983},
   { "minValue": 57, "maxValue": 189, "count": 1344} ],
}
```

What's useful about the explicit keys are we could add `sum, average`

**Pull request closed without merging**
