### PR TITLE
Feature/grouped bar

### LINKED ISSUE #160: Support Grouped Bar Charts
split out #148 

https://www.google.com/search?q=grouped+bar+chart&tbm=isch

awesome

### PR DESCRIPTION
**Pull request by ajturner**
Resolves #160

future improvements

- better hover tooltips
- remove FeatureService `attributes.` prefix

grouped_bar_chart___esri_cedar

### CODE REVIEW

**Comment by ddred11** [comment]
@ajturner Looks awesome!  Seems like we would want more spacing between grouped bars. In both examples above labeling can be hard to read. Wondering if we would also limit the number of categories in a given chart? Or would that be the application eventually that would do so?

**Comment by ajturner** [comment]
@ddred11 for now I think that apps choose a max based on their available space.

Generally I'm interested in how the data could inform limiting by rank order or 'significant' features.

**Comment by ddred11** [comment]
That sounds interesting... how does data inform "significant"? Just wondering what you mean by that. I am gathering that rank order is just the top or bottom x values...

**Comment by ajturner** [comment]
@ddred11 indeed that is the question. statistical outliers - where is there a large difference between the grouped data? or total value differences. Researching that in [Fews](http://www.amazon.com/Now-You-See-Visualization-Quantitative/dp/0970601980) and [Cleveland](http://www.amazon.com/Visualizing-Data-William-S-Cleveland/dp/0963488406)

**Pull request merged**
