### PR TITLE
Fixes chart fitting in frame and adds size updating

### PR DESCRIPTION
**Pull request by ajturner**
- Made all charts `"padding": "strict"` which handles the entire chart fitting within the width and height
- Added API
 - `chart.show({'width': 400, 'height': 300})` for explicit size
 - `chart.width= ` and `chart.height=` then `chart.update()` to update later
 - implicit chart size by using `elementId` size.
- Added new example page `sizes.html` that shows how this works.

**Next Step** add `responsive:true` to API per #89 - but that will just be an internal event handler.

cedar_sizes

/cc @abakirov @tomwayson @benheb

### CODE REVIEW

**Comment by tomwayson** [comment]
This API is intuitive and sure makes it easy to have responsive charts.

I'm not even sure we need to include the API suggestions I made in #89 b/c it's so easy to do externally. Also, what if someone overrides `height`, `width`, and/or `padding` on a chart they want to be responsive? Will it still work to simply call `.update()` or will we have to include the logic that calculates the height of the container? See [my recent comment](https://github.com/Esri/cedar/issues/89#issuecomment-108216489) and let me know if you still want to pursue that at this time.

I updated a couple of the custom specs to use `padding: "strict"` b/c their charts were overflowing into the right nav menu.

Also I noticed that the pie chart labels are off now, but I did not fix this. Any ideas:

screen shot 2015-06-02 at 10 52 10 pm

**Comment by tomwayson** [comment]
Also, I've noticed that calling update can (and does in both re-sizable examples docs) cause the data be re-fetched from the server. Seems like it would be good to provide a way for the user to just resize the chart w/ the existing data, Also seems like that should be prioritized over (and would be a pre-cursor to) adding API for users to tell a chart to be responsive and manage it's own re-sizing.

I can imaging a couple of APIs for this:
1) pass a flag to the `update()` method that indicates that it should not refresh the data - like `update({useCache: true}) // defaults to false`
2) decouple the sizing logic into to it's own function `resize()` (harder)

Thoughts? Feelings?

**Comment by ajturner** [comment]
I think a flag in update is the start. Many cases where I've changed style or size and don't want data fetched.

How about `updateData: true`

**Comment by tomwayson** [comment]
OK, just to clarify, the default would be to **NOT** update the data but if you pass in a truthy value for the `updateData` option it would update the data, right?

LMK and I'll add it.

**Comment by ajturner** [comment]
I think so. Having data update is a great feature, but probably less common.

So default `updateData: false`

/cc @benheb @dbouwman

**Comment by ajturner** [comment]
Fixed pie charts by adding a new input parameter `radius`.


esri_cedar

```javascript
  var dataset = {
    "url":"http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Education_WebMercator/MapServer/5",
    "mappings":{
      "group": {"field":"ZIP_CODE","label":"ZIP Code"},
      "count": {"field":"TOTAL_STUD","label":"Total Students"},
      "radius": 270
    }
  };
  chart.dataset = dataset;

  chart.show({
    elementId: "#chart",
    width: 600,
    height: 600
  });  
```

Note that this isn't styled b/c PR #96 is not merged and not part of this history.

**Comment by abakirov** [comment]
@ajturner 
Thank you for doing this! It will really help us with the charts in our app.

**Comment by ajturner** [comment]
merging - 

note @abakirov there are some API changes to Pie and Bar charts

**Pull request merged**
