### PR TITLE
added redraw() to API

### LINKED ISSUE #100: Add update(updateData: true)
default `false`, optional `true`

### PR DESCRIPTION
**Pull request by tomwayson**
allows for resizing and re-drawing w/o having to update data
sizing and responsive example pages use the new method

resolves #100 - after looking into it, it was easier (and probably more intuitive) to add a `redraw()` method than passing options to the `update()`

### CODE REVIEW

**Comment by ajturner** [comment]
Except does it semantically break between Cedar and Vega. Meaning does Vega update reload data - or just rerender based on the specification changes?

**Comment by tomwayson** [comment]
Good point, I'll have to check...

**Comment by tomwayson** [comment]
Looks at vega's docs, at first it seemed that their view's `render()` function might have been a parallel to my `redraw()`

https://github.com/trifacta/vega/wiki/Runtime#view-component-api

I tried using that in place of `update()` on this line: https://github.com/Esri/cedar/blob/redraw/src/cedar.js#L400

However, that did not work, so it looks like vega's `update()` is needed for a resize.

One idea is to rename my `redraw()` function to `resize()` and add an optional object parameter w/ width/height props that can override the ones set in the constructor:

```js

// sets chart height/width to match containing div
chart.resize();

// sets explicit chart height/width
chart.resize({
  height: 400,
  width: 200
});

// just update the width (if height was not previously explicitly it will be set to current div height)
chart.resize({
  width: 400
});
```

Alternatively we could implement the original API suggested in #100.

Thoughts, feelings?

**Comment by ajturner** [comment]
There may be times we want the chart to redraw itself that is not just a resize.

I'm still a fan of #100 because it's the same concept and IMO data should be explicit.

**Comment by tomwayson** [comment]
OK, I'll implement this as per #100

**Comment by ajturner** [comment]
closing PR because we have to move to a `develop` branch

**Pull request closed without merging**
